# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CqXVmnvKLZpP0OTLO+3DlYRCcLrWlmTDnDMwrTZlYFPRuARDgM1b9j57c1gRlFM1I5MoX1/V4qZaV3UMDF6mTV9ojz8I0oRO010cUiQa97JHA3jdx+0TEgBYYK5gTYkHSo2kczEZlY0Fkb6cr16cs477v6FsE/gpW0AxoDIe+xmn4i67qrCgrj46aeCnIuM2lw865dWqqXdwF0gDbI0xgEHQo0h7uEuaCT88ZUWpVADdnEmLU3iyt8Jcy5zydue8ZEFuzbBJGGLu16umqJTWK4AA55xS96FuQa0yEj3HJYRjWd/iwFlXEdqNHUdGweOq9EMoDhrP7rDfA5zXalqM30kPXokC+QYFzqC7tr8Aw2nMaG3lxSn4ztW2h+z10mcIluzXJ+3ZwJuoy1+ELF8vvFBiJ16ApjA+TOUigZs/K1ido3BXWKJuX6JrYCrne7rpgVW1jtj9zgt9k2kVOg2RUOq9aU4ZuIfktOQcm8dluwXQcbj3l/057BpcYl2hQQk8FlTg1zF6NVH5G7XbEH5Lm4t2lcPWJusJdl1Nrfwr7qeHPqlkItW1xDNalZ+rmb8iCRo+ykS2nf+KKVvoWU/ei40oCKJ0Bly2/NA51eIMWTT5AJq+JvZGWRyMLXhP7bQCf3AJhFF5LRZTg2YI2ewh8WeQwgveZmlMV5vcvlTPBvI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda install numpy=1.9.3=py36_blas_openblas_201 openblas=0.2.19
  - python -c "import numpy.linalg.linalg"
