# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ov4nUdga5WNh9X38+KqfK6cIjp7P5w6iPTsvW9tBYeiUZDKBelwZXjDtAs7AUNxLkqn8QucpowWhgIF838/iTynvTqbNOgoW8p07oqHdfbIP3of7aZ4zC2gbGPka9wiCj25mrEbSn931THi5bHrmxgqFMA9QBbdiIN0yzEIE46VGnz674aCmjeH6SeqKCPY6N0j8gvFZMWcb6EDhJHo5HnluluIR9V6sTJwlU5KRuUk+YTUaRg3brWjzQbLPE5WYZMdtwQNgAMyuYW1ly4vMy2f2acwJmfpSDlxMbarAhtO7QjZ3oPWMrbBf7qCeyAmp9chP078EPLXPAVDMUZkiAbOkLDOqAMQbV98rycFnN8/SbGlNhsUdaUAMjYbJOBiwH27JA39q8LPWH77MVQhQkSKHiOFXQoDFguCP8BI4Nz1wwf8G+bBxSzsnTRY2iCDSizMu3w+cHgWUTx7Mb/vVBHQMVnwriwInEWSA7QfIX1HAdTe3p22o5FZDKZFJK4uyoGKXM8Y9Ld6YpJ4LvT+/AZOxoEDt4mye//UOMRsQBx7/KE/l8zMuIFvDWLFTUZVJJaB5d2wvPrYl4B7beh1Js2L2GHgtI8b4Z6zEp3j1lvzhpwilvvIJ/T6aBIR8pzvWuMffAj4dfCsF+tvcinT0Nt4IZM+vDNqsb+DIyGfax7w="

matrix:
  include:
    - env: CONFIG=osx_python2.7 MINICONDA_OS=MacOSX-x86_64
      os: osx
      osx_image: xcode6.4
    - env: CONFIG=osx_python3.5 MINICONDA_OS=MacOSX-x86_64
      os: osx
      osx_image: xcode6.4
    - env: CONFIG=osx_python3.6 MINICONDA_OS=MacOSX-x86_64
      os: osx
      osx_image: xcode6.4

    - env: CONFIG=linux_ppc64le_python2.7 MINICONDA_OS=Linux-ppc64le
      os: linux-ppc64le
    - env: CONFIG=linux_ppc64le_python3.5 MINICONDA_OS=Linux-ppc64le
      os: linux-ppc64le
    - env: CONFIG=linux_ppc64le_python3.6 MINICONDA_OS=Linux-ppc64le
      os: linux-ppc64le


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          echo ""
          echo "Removing homebrew from Travis CI to avoid conflicts."
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -fq
          rm ~/uninstall_homebrew
      fi


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-${MINICONDA_OS}.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source ${HOME}/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
